import os
from datetime import datetime, timedelta

FILE_OBS_ADCP2 = os.path.expanduser('~/GitHub-repo/TSSM_PF0_demo/src/validation/ADCP2_new.csv')
FILE_OBS_ADCP3 = os.path.expanduser('~/GitHub-repo/TSSM_PF0_demo/src/validation/ADCP3_new.csv')
WORK_DIR = os.path.expanduser('~/GitHub-repo/TSSM_unify_main/TSSM/src')
BASE_FILE = 'outputs/diagnostic_detectors-adcp.hdf5'
cases = [
        {
            'tag': 'PF0 (nM x 0.8) ADCP2',
            'file_obs': FILE_OBS_ADCP2,
            # 'file_sim': os.path.expanduser(f'{WORK_DIR}/case_PF0-G_nM_08_Emils/{BASE_FILE}'),
            'file_sim': os.path.expanduser(f'{WORK_DIR}/case_PF0-G_visc5_nM08/outputs/diagnostic_detectors-adcp.hdf5'),
            'idx_col': 15,
            't0obs': datetime(2017, 8, 3, 11, 1, 50),
            't0sim': datetime(2017,8,1,0,0,0),
            'dtobs': timedelta(seconds=100),
            'dtsim': timedelta(seconds=100),
            'shift': 0,
        },
        {
            'tag': 'PF0 (nM x 0.8) ADCP3',
            'file_obs': FILE_OBS_ADCP3,
            # 'file_sim': os.path.expanduser(f'{WORK_DIR}/case_PF0-G_nM_08_Emils/{BASE_FILE}'),
            'file_sim': os.path.expanduser(f'{WORK_DIR}/case_PF0-G_visc5_nM08/outputs/diagnostic_detectors-adcp.hdf5'),
            'idx_col': 16,
            't0obs': datetime(2017, 8, 3, 11, 1, 50),
            't0sim': datetime(2017,8,1,0,0,0),
            # 't_end': datetime(2017,8,29, 22,0,0),
            'dtobs': timedelta(seconds=100),
            'dtsim': timedelta(seconds=100),
            'shift': 0,
        },
        {
            'tag': 'PF0 (nM x 1.0) ADCP2',
            'file_obs': FILE_OBS_ADCP2,
            # 'file_sim': os.path.expanduser(f'{WORK_DIR}/case_PF0-G_nM_10/{BASE_FILE}'),  
            'file_sim': os.path.expanduser(f'{WORK_DIR}/case_PF0-G_visc_5/{BASE_FILE}'),
            'idx_col': 15,
            't0obs': datetime(2017, 8, 3, 11, 1, 50),
            't0sim': datetime(2017,8,1,0,0,0),
            'dtobs': timedelta(seconds=100),
            'dtsim': timedelta(seconds=100),
            'shift': 0,
        },
        {
            'tag': 'PF0 (nM x 1.0) ADCP3',
            'file_obs': FILE_OBS_ADCP3,
            # 'file_sim': os.path.expanduser(f'{WORK_DIR}/case_PF0-G_nM_10/{BASE_FILE}'),  
            'file_sim': os.path.expanduser(f'{WORK_DIR}/case_PF0-G_visc_5/{BASE_FILE}'),
            'idx_col': 16,
            't0obs': datetime(2017, 8, 3, 11, 1, 50),
            't0sim': datetime(2017,8,1,0,0,0),
            # 't_end': datetime(2017,8,29, 22,0,0),
            'dtobs': timedelta(seconds=100),
            'dtsim': timedelta(seconds=100),
            'shift': 0,
        },
        {
            'tag': 'PF0 (nM x 1.1) ADCP2',
            'file_obs': FILE_OBS_ADCP2,
            # 'file_sim': os.path.expanduser(f'{WORK_DIR}/case_PF0-G_nM_11/{BASE_FILE}'),
            'file_sim': os.path.expanduser(f'{WORK_DIR}/case_PF0-G_visc5_nM11/{BASE_FILE}'),
            'idx_col': 15,
            't0obs': datetime(2017, 8, 3, 11, 1, 50),
            't0sim': datetime(2017,8,1,0,0,0),  #
            'dtobs': timedelta(seconds=100),
            'dtsim': timedelta(seconds=100),
            'shift': 0,
        },
        {
            'tag': 'PF0 (nM x 1.1) ADCP3',
            'file_obs': FILE_OBS_ADCP3,
            # 'file_sim': os.path.expanduser(f'{WORK_DIR}/case_PF0-G_nM_11/{BASE_FILE}'),
            'file_sim': os.path.expanduser(f'{WORK_DIR}/case_PF0-G_visc5_nM11/{BASE_FILE}'),
            'idx_col': 16,
            't0obs': datetime(2017, 8, 3, 11, 1, 50),
            't0sim': datetime(2017,8,1,0,0,0),
            # 't_end': datetime(2017,8,29, 22,0,0),
            'dtobs': timedelta(seconds=100),
            'dtsim': timedelta(seconds=100),
            'shift': 0,
        },
        {
            'tag': 'PF0 (nM x 1.2) ADCP2',
            'file_obs': FILE_OBS_ADCP2,
            # 'file_sim': os.path.expanduser(f'{WORK_DIR}/case_PF0-G_nM_12_Emils/{BASE_FILE}'),
            'file_sim': os.path.expanduser(f'{WORK_DIR}/case_PF0-G_visc5_nM12/{BASE_FILE}'),
            'idx_col': 15,
            't0obs': datetime(2017, 8, 3, 11, 1, 50),
            't0sim': datetime(2017,8,1,0,0,0),
            'dtobs': timedelta(seconds=100),
            'dtsim': timedelta(seconds=100),
            'shift': 0,
        },
        {
            'tag': 'PF0 (nM x 1.2) ADCP3',
            'file_obs': FILE_OBS_ADCP3,
            # 'file_sim': os.path.expanduser(f'{WORK_DIR}/case_PF0-G_nM_12_Emils/{BASE_FILE}'),
            'file_sim': os.path.expanduser(f'{WORK_DIR}/case_PF0-G_visc5_nM12/{BASE_FILE}'),
            'idx_col': 16,
            't0obs': datetime(2017, 8, 3, 11, 1, 50),
            't0sim': datetime(2017,8,1,0,0,0),
            # 't_end': datetime(2017,8,29, 22,0,0),
            'dtobs': timedelta(seconds=100),
            'dtsim': timedelta(seconds=100),
            'shift': 0,
        },
        {
            'tag': 'PF1 (nM x 0.8) ADCP2',
            'file_obs': FILE_OBS_ADCP2,
            # 'file_sim': os.path.expanduser(f'{WORK_DIR}/case_PF1-G_nM_08/{BASE_FILE}'),
            'file_sim': os.path.expanduser(f'{WORK_DIR}/case_PF1-G_visc5_nM08/outputs/diagnostic_detectors-adcp_n.hdf5'),
            'idx_col': 15,
            't0obs': datetime(2017, 8, 3, 11, 1, 50),
            't0sim': datetime(2017,8,1,0,0,0),  # long ramp-run  (2017,7,30,0,0,0)
            't_end': datetime(2017,8,31,0,0,0),
            'dtobs': timedelta(seconds=100),
            'dtsim': timedelta(seconds=100),
            'shift': 0,
        },
        {
            'tag': 'PF1 (nM x 0.8) ADCP3',
            'file_obs': FILE_OBS_ADCP3,
            # 'file_sim': os.path.expanduser(f'{WORK_DIR}/case_PF1-G_nM_08/{BASE_FILE}'),
            'file_sim': os.path.expanduser(f'{WORK_DIR}/case_PF1-G_visc5_nM08/outputs/diagnostic_detectors-adcp_n.hdf5'),
            'idx_col': 16,
            't0obs': datetime(2017, 8, 3, 11, 1, 50),
            't0sim': datetime(2017,8,1,0,0,0),  # long ramp-run  (2017,7,30,0,0,0)
            't_end': datetime(2017,8,31,0,0,0),
            'dtobs': timedelta(seconds=100),
            'dtsim': timedelta(seconds=100),
            'shift': 0,
        },
        {
            'tag': 'PF1 (nM x 1.0) ADCP2',
            'file_obs': FILE_OBS_ADCP2,
            # 'file_sim': os.path.expanduser(f'{WORK_DIR}/case_PF1-G_nM_10/{BASE_FILE}'),
            'file_sim': os.path.expanduser(f'{WORK_DIR}/case_PF1-G_visc_5/outputs/diagnostic_detectors-adcp_join.hdf5'),
            'idx_col': 15,
            't0obs': datetime(2017, 8, 3, 11, 1, 50),
            't0sim': datetime(2017,8,1,0,0,0),
            'dtobs': timedelta(seconds=100),
            'dtsim': timedelta(seconds=100),
            'shift': 0,
        },
        {
            'tag': 'PF1 (nM x 1.0) ADCP3',
            'file_obs': FILE_OBS_ADCP3,
            # 'file_sim': os.path.expanduser(f'{WORK_DIR}/case_PF1-G_nM_10/{BASE_FILE}'),
            'file_sim': os.path.expanduser(f'{WORK_DIR}/case_PF1-G_visc_5/outputs/diagnostic_detectors-adcp_join.hdf5'),
            'idx_col': 16,
            't0obs': datetime(2017, 8, 3, 11, 1, 50),
            't0sim': datetime(2017,8,1,0,0,0),
            'dtobs': timedelta(seconds=100),
            'dtsim': timedelta(seconds=100),
            'shift': 0,
        },
        {
            'tag': 'PF1 (nM x 1.1) ADCP2',
            'file_obs': FILE_OBS_ADCP2,
            # 'file_sim': os.path.expanduser(f'{WORK_DIR}/case_PF1-G_nM_11_Emils/{BASE_FILE}'),
            'file_sim': os.path.expanduser(f'{WORK_DIR}/case_PF1-G_visc5_nM11/outputs/diagnostic_detectors-adcp_cutall.hdf5'),
            'idx_col': 15,
            't0obs': datetime(2017, 8, 3, 11, 1, 50),
            't0sim': datetime(2017,8,1,0,0,0),
            'dtobs': timedelta(seconds=100),
            'dtsim': timedelta(seconds=100),
            'shift': 0,
        },
        {
            'tag': 'PF1 (nM x 1.1) ADCP3',
            'file_obs': FILE_OBS_ADCP3,
            # 'file_sim': os.path.expanduser(f'{WORK_DIR}/case_PF1-G_nM_11_Emils/{BASE_FILE}'),
            'file_sim': os.path.expanduser(f'{WORK_DIR}/case_PF1-G_visc5_nM11/outputs/diagnostic_detectors-adcp_cutall.hdf5'),
            'idx_col': 16,
            't0obs': datetime(2017, 8, 3, 11, 1, 50),
            't0sim': datetime(2017,8,1,0,0,0),
            'dtobs': timedelta(seconds=100),
            'dtsim': timedelta(seconds=100),
            'shift': 0,
        },
        {
            'tag': 'PF1 (nM x 1.2) ADCP2',
            'file_obs': FILE_OBS_ADCP2,
            # 'file_sim': os.path.expanduser(f'{WORK_DIR}/case_PF1-G_nM_12/{BASE_FILE}'),
            'file_sim': os.path.expanduser(f'{WORK_DIR}/case_PF1-G_visc5_nM12/outputs/diagnostic_detectors-adcp_new.hdf5'),
            'idx_col': 15,
            't0obs': datetime(2017, 8, 3, 11, 1, 50),
            't0sim': datetime(2017,8,1,0,0,0),  # long ramp-run  (2017,7,30,0,0,0)
            'dtobs': timedelta(seconds=100),
            'dtsim': timedelta(seconds=100),
            'shift': 0,
        },
        {
            'tag': 'PF1 (nM x 1.2) ADCP3',
            'file_obs': FILE_OBS_ADCP3,
            # 'file_sim': os.path.expanduser(f'{WORK_DIR}/case_PF1-G_nM_12/{BASE_FILE}'),
            'file_sim': os.path.expanduser(f'{WORK_DIR}/case_PF1-G_visc5_nM12/outputs/diagnostic_detectors-adcp_new.hdf5'),
            'idx_col': 16,
            't0obs': datetime(2017, 8, 3, 11, 1, 50),
            't0sim': datetime(2017,8,1,0,0,0),  # long ramp-run  (2017,7,30,0,0,0)
            'dtobs': timedelta(seconds=100),
            'dtsim': timedelta(seconds=100),
            'shift': 0,
        },

        {
            'tag': 'PF2 (nM x 0.8) ADCP2',
            'file_obs': FILE_OBS_ADCP2,
            # 'file_sim': os.path.expanduser(f'{WORK_DIR}/case_PF2-G_nM_08_Connor/{BASE_FILE}'),
            'file_sim': os.path.expanduser(f'{WORK_DIR}/case_PF2-G_visc5_nM_08/{BASE_FILE}'),
            'idx_col': 15,
            't0obs': datetime(2017, 8, 3, 11, 1, 50),
            't0sim': datetime(2017,8,1,0,0,0),
            'dtobs': timedelta(seconds=100),
            'dtsim': timedelta(seconds=100),
            'shift': 0,
        },
        {
            'tag': 'PF2 (nM x 0.8) ADCP3',
            'file_obs': FILE_OBS_ADCP3,
            # 'file_sim': os.path.expanduser(f'{WORK_DIR}/case_PF2-G_nM_08_Connor/{BASE_FILE}'),
            'file_sim': os.path.expanduser(f'{WORK_DIR}/case_PF2-G_visc5_nM_08/{BASE_FILE}'),
            'idx_col': 16,
            't0obs': datetime(2017, 8, 3, 11, 1, 50),
            't0sim': datetime(2017,8,1,0,0,0),
            'shift': 0,
        },
        {
            'tag': 'PF2 (nM x 1.0) ADCP2',
            'file_obs': FILE_OBS_ADCP2,
            # 'file_sim': os.path.expanduser(f'{WORK_DIR}/case_PF2-G_nM_10_new_bump/{BASE_FILE}'),
            'file_sim': os.path.expanduser(f'{WORK_DIR}/case_PF2-G_visc_5/outputs/diagnostic_detectors-adcp_join.hdf5'),
            'idx_col': 15,
            't0obs': datetime(2017, 8, 3, 11, 1, 50),
            't0sim': datetime(2017,8,1,0,0,0),
            'dtobs': timedelta(seconds=100),
            'dtsim': timedelta(seconds=100),
            'shift': 0,
        },
        {
            'tag': 'PF2 (nM x 1.0) ADCP3',
            'file_obs': FILE_OBS_ADCP3,
            # 'file_sim': os.path.expanduser(f'{WORK_DIR}/case_PF2-G_nM_10_new_bump/{BASE_FILE}'),
            'file_sim': os.path.expanduser(f'{WORK_DIR}/case_PF2-G_visc_5/outputs/diagnostic_detectors-adcp_join.hdf5'),
            'idx_col': 16,
            't0obs': datetime(2017, 8, 3, 11, 1, 50),
            't0sim': datetime(2017,8,1,0,0,0),
        },
        {
            'tag': 'PF2 (nM x 1.1) ADCP2',
            'file_obs': FILE_OBS_ADCP2,
            'file_sim': os.path.expanduser(f'{WORK_DIR}/case_PF2-G_visc5_nM_11/{BASE_FILE}'),
            # 'file_sim': os.path.expanduser(f'{WORK_DIR}/case_PF2-G_nM_11/{BASE_FILE}'),
            'idx_col': 15,
            't0obs': datetime(2017, 8, 3, 11, 1, 50),
            't0sim': datetime(2017,8,1,0,0,0),
            'dtobs': timedelta(seconds=100),
            'dtsim': timedelta(seconds=100),
            'shift': 0,
        },
        {
            'tag': 'PF2 (nM x 1.1) ADCP3',
            'file_obs': FILE_OBS_ADCP3,
            'file_sim': os.path.expanduser(f'{WORK_DIR}/case_PF2-G_visc5_nM_11/{BASE_FILE}'),
            # 'file_sim': os.path.expanduser(f'{WORK_DIR}/case_PF2-G_nM_11/{BASE_FILE}'),
            'idx_col': 16,
            't0obs': datetime(2017, 8, 3, 11, 1, 50),
            't0sim': datetime(2017,8,1,0,0,0),
            'shift': 0,
        },
        {
            'tag': 'PF2 (nM x 1.2) ADCP2',
            'file_obs': FILE_OBS_ADCP2,
            # 'file_sim': os.path.expanduser(f'{WORK_DIR}/case_PF2-G_nM_12_hotstart/{BASE_FILE}'),
            'file_sim': os.path.expanduser(f'{WORK_DIR}/case_PF2-G_visc5_nM12/outputs/diagnostic_detectors-adcp_cutall.hdf5'),
            'idx_col': 15,
            't0obs': datetime(2017, 8, 3, 11, 1, 50),
            't0sim': datetime(2017,8,1,0,0,0),
            't_end': datetime(2017,8,27, 8,0,0),
            # 't_end': datetime(2017,8,15, 0,0,0),
            # 't_end': datetime(2017,8,11, 14,0,0),
            'dtobs': timedelta(seconds=100),
            'dtsim': timedelta(seconds=100),
            'shift': 0,
        },
        {
            'tag': 'PF2 (nM x 1.2) ADCP3',
            'file_obs': FILE_OBS_ADCP3,
            # 'file_sim': os.path.expanduser(f'{WORK_DIR}/case_PF2-G_nM_12_hotstart/{BASE_FILE}'),
            'file_sim': os.path.expanduser(f'{WORK_DIR}/case_PF2-G_visc5_nM12/outputs/diagnostic_detectors-adcp_cutall.hdf5'),
            'idx_col': 16,
            't0obs': datetime(2017, 8, 3, 11, 1, 50),
            't0sim': datetime(2017,8,1,0,0,0),
            't_end': datetime(2017,8,27, 8,0,0),
            # 't_end': datetime(2017,8,15, 0,0,0),
            # 't_end': datetime(2017,8,11, 14,0,0),
            'shift': 0,
        },
    ]
    